### ISSUE TITLE
Buffer is not defined with 0.2.3

### ISSUE THREAD

**Issue by castasamu** [aldeed/js-message-box#15] opened 2020-04-22 14:47 UTC
I try use simpl-schema but with version 0.2.3 the console says:

Buffer is not defined.

**Comment by dovydaskukalis** [comment] 2020-04-22 14:53
Same issue, caused by adding `deep-extend` as a dep. https://github.com/unclechu/node-deep-extend/issues/42

**Comment by pward123** [comment] 2020-04-23 10:58
See https://github.com/aldeed/js-message-box/pull/9

**Comment by aldeed** [comment] 2020-04-23 19:45
Ha, we've come full circle. Forgot about that issue. For those seeing this, is it only with React Native?

**Comment by dovydaskukalis** [comment] 2020-04-23 19:57
> Ha, we've come full circle. Forgot about that issue. For those seeing this, is it only with React Native?

For me it’s Meteor. I just posted a similar issue. What’s interesting is that we already include` global.Buffer = global.Buffer || require('buffer').Buffer` before importing anything using simple-schema as we have another module which needs buffers but for some reason this one crashes website as if buffer doesn’t exist.

**Comment by aldeed** [comment] 2020-04-23 20:19
Might switch to [deepmerge](https://www.npmjs.com/package/deepmerge). It's smaller than most of the others and seemingly maintained. I don't see any references to `Buffer` in its codebase.

**Comment by aldeed** [comment] 2020-04-23 20:45
Fixed in 0.2.4

**Closed as completed** 2020-04-23 20:44 UTC

**Comment by aldeed** [comment] 2020-04-23 21:03
Additional fix in 0.2.5
